### ISSUE TITLE
Unified implementation

### ISSUE THREAD

**Issue by nihil-admirari** [SimonLammer/anki-persistence#77]
`sessionStorage` works in AnkiDesktop, at least on Linux in latest version.

Also, JavaScript modules provide a third implementation option. Modules are never initialised more than once, so module state is preserved across imports from the front and the back of a card. Placing the following into a media folder:

```js
export PERSISTENCE = new Map();
```

and importing it from a template gives the ability to persist arbitrary data, not just JSON. It work on desktop and AnkiWeb. Unfortunately, it doesn't work in AnkiDroid, since the latter fully refreshes the entire page when switching to the back of the card. AnkiMobile is untested.

**Comment by SimonLammer** [comment]
> `sessionStorage` works in AnkiDesktop, at least on Linux in latest version.

Good to know. Without any testing, I guess it will automatically be chosen if it works, because sessionStorage is the default persistence mechanism - https://github.com/SimonLammer/anki-persistence/blob/master/script.js#L105.

> Also, JavaScript modules provide a third implementation option. Modules are never initialized more than once, so module state is preserved across imports from the front and the back of a card. Placing the following into a media folder:
> 
> ```js
> export PERSISTENCE = new Map();
> ```
> 
> and importing it from a template gives the ability to persist arbitrary data, not just JSON. It work on desktop and AnkiWeb. Unfortunately, it doesn't work in AnkiDroid, since the latter fully refreshes the entire page when switching to the back of the card. AnkiMobile is untested.

While I agree it would nice not to require persisted data to be JSON-serializable, unified cross-platform behaviour is more important to this project (particularly since I don't see a use-case for non-JSON-serializable persistence (that couldn't be worked-around with JSON-serizalizable persistence)).
